const data = [
  {
    courseId: 1,
    courseName: "toeic 500+",
    courseTopics: [
      {
        topicId: 1,
        topicName: "Contract",
        wordlist: [
          { eng: "Address", pronounce: "əˈdrɛs", viet: "Giải quyết (vấn đề)" },
          { eng: "Avoid", pronounce: "əˈvɔɪd", viet: "Tránh" },
          {
            eng: "Demonstrate",
            pronounce: "ˈdɛmənstreɪt",
            viet: "Bày tỏ, biểu lộ, cho thấy",
          },
          { eng: "Develop", pronounce: "dɪˈvɛləp", viet: "Phát triển" },
          { eng: "Evaluate", pronounce: "ɪˈvæljʊeɪt", viet: "Đánh giá" },
          { eng: "Gather", pronounce: "ˈgæðə", viet: "Tập hợp, thu thập" },
          { eng: "Offer", pronounce: "ˈɒfəˌ", viet: "Đề xuất, đề nghị" },
          { eng: "Primarily", pronounce: "ˈpraɪmərɪli", viet: "Chính" },
          { eng: "Risk", pronounce: "rɪsk", viet: "Sự rủi ro" },
          { eng: "Strategy", pronounce: "ˈstrætɪʤi", viet: "Chiến lược" },
          {
            eng: "Strong",
            pronounce: "strɒŋ",
            viet: "Khỏe mạnh, tốt, bền bỉ, …",
          },
          {
            eng: "Substitution",
            pronounce: "sʌbstɪˈtjuːʃən",
            viet: "Sự thay thế",
          },
        ],
      },
      {
        topicId: 2,
        topicName: "Marketing",
        wordlist: [
          { eng: "advanced", pronounce: " ədˈvɑːnst ", viet: " tiên tiến " },
          { eng: "chain", pronounce: " ʧeɪn ", viet: " chuỗi " },
          { eng: "checkin", pronounce: " checkin ", viet: " đăng ký khi đến " },
          { eng: "confirm", pronounce: " kənˈfɜːm ", viet: " xác nhận " },
          { eng: "expect", pronounce: " ɪksˈpɛkt ", viet: " trông đợi " },
          {
            eng: "housekeeper",
            pronounce: " ˈhaʊsˌkiːpə ",
            viet: " nhân viên dọn phòng ",
          },
          { eng: "notify", pronounce: " ˈnəʊtɪfaɪ ", viet: " thông báo " },
          { eng: "preclude", pronounce: " prɪˈkluːd ", viet: " ngăn cản " },
          {
            eng: "reservation",
            pronounce: " ˌrɛzəˈveɪʃən ",
            viet: " sự đặt chỗ trước ",
          },
          { eng: "quote", pronounce: " kwəʊt ", viet: " báo giá " },
          { eng: "rate", pronounce: " reɪt ", viet: " mức giá " },
          { eng: "service", pronounce: " ˈsɜːvɪs ", viet: " dịch vụ " },
        ],
      },
      {
        topicId: 3,
        topicName: "General Travel",
        wordlist: [
          { eng: "agent", pronounce: "ˈeɪʤənt", viet: "đại lý" },
          { eng: "announcement", pronounce: "əˈnaʊnsmənt", viet: "thông báo" },
          {
            eng: "beverage",
            pronounce: "ˈbɛvərɪʤ",
            viet: "thức uống, đồ uống",
          },
          { eng: "blanket", pronounce: "ˈblæŋkɪt", viet: "Chăn, mền" },
          { eng: "board", pronounce: "bɔːd", viet: "lên máy bay" },
          { eng: "claim", pronounce: "kleɪm", viet: "nhận lại" },
          { eng: "delay", pronounce: "dɪˈleɪ", viet: "trì hoãn" },
          { eng: "depart", pronounce: "dɪˈpɑːt", viet: "khởi hành" },
          {
            eng: "embarkation",
            pronounce: "ˌɛmbɑːˈkeɪʃən",
            viet: "sự cho lên tàu",
          },
          {
            eng: "itinerary",
            pronounce: "aɪˈtɪnərəri",
            viet: "hành trình, lịch trình",
          },
          {
            eng: "prohibit",
            pronounce: "prəˈhɪbɪt",
            viet: "cấm, ngăn cấm, ngăn chặn",
          },
          { eng: "valid", pronounce: "ˈvælɪd", viet: "có hiệu lực" },
        ],
      },
      {
        topicId: 4,
        topicName: "Business Planning",
        wordlist: [
          {
            eng: "Correspondence",
            pronounce: "kɒrɪsˈpɒndəns",
            viet: "thư từ, quan hệ thư từ",
          },
          { eng: "assemble", pronounce: "əˈsɛmbl", viet: "thu thập, tập hợp" },
          {
            eng: "beforehand",
            pronounce: "bɪˈfɔːhænd",
            viet: "sẵn, có sẵn, trước, sớm",
          },
          {
            eng: "complication",
            pronounce: "kɒmplɪˈkeɪʃən",
            viet: "sự phức tạp",
          },
          {
            eng: "courier",
            pronounce: "kʊrɪə",
            viet: "người đưa thư, chuyển phát",
          },
          {
            eng: "express",
            pronounce: "ɪksˈprɛs",
            viet: "tốc hành, nhanh, hỏa tốc",
          },
          { eng: "fold", pronounce: "fəʊld", viet: "gấp, gập" },
          {
            eng: "layout",
            pronounce: "leɪaʊt",
            viet: "sự bố trí, trang trí giấy",
          },
          { eng: "mention", pronounce: "mɛnʃən", viet: "đề cập" },
          { eng: "petition", pronounce: "pɪˈtɪʃən", viet: "sự kiến nghị" },
          { eng: "proof", pronounce: "pruːf", viet: "tìm lỗi, kiểm lỗi" },
          {
            eng: "proof",
            pronounce: "pruːf",
            viet: "bằng chứng, chứng cớ",
          },
          { eng: "revise", pronounce: "rɪˈvaɪz", viet: "sửa lại" },
        ],
      },
    ],
  },
  {
    courseId: 2,
    courseName: "toeic 200000++",
    courseTopics: [
      {
        topicId: 5,
        topicName: "Contract",
        wordlist: [
          { eng: "Address", pronounce: "əˈdrɛs", viet: "Giải quyết (vấn đề)" },
          { eng: "Avoid", pronounce: "əˈvɔɪd", viet: "Tránh" },
          {
            eng: "Demonstrate",
            pronounce: "ˈdɛmənstreɪt",
            viet: "Bày tỏ, biểu lộ, cho thấy",
          },
          { eng: "Develop", pronounce: "dɪˈvɛləp", viet: "Phát triển" },
          { eng: "Evaluate", pronounce: "ɪˈvæljʊeɪt", viet: "Đánh giá" },
          { eng: "Gather", pronounce: "ˈgæðə", viet: "Tập hợp, thu thập" },
          { eng: "Offer", pronounce: "ˈɒfəˌ", viet: "Đề xuất, đề nghị" },
          { eng: "Primarily", pronounce: "ˈpraɪmərɪli", viet: "Chính" },
          { eng: "Risk", pronounce: "rɪsk", viet: "Sự rủi ro" },
          { eng: "Strategy", pronounce: "ˈstrætɪʤi", viet: "Chiến lược" },
          {
            eng: "Strong",
            pronounce: "strɒŋ",
            viet: "Khỏe mạnh, tốt, bền bỉ, …",
          },
          {
            eng: "Substitution",
            pronounce: "sʌbstɪˈtjuːʃən",
            viet: "Sự thay thế",
          },
        ],
      },
      {
        topicId: 6,
        topicName: "Marketing",
        wordlist: [
          { eng: "advanced", pronounce: " ədˈvɑːnst ", viet: " tiên tiến " },
          { eng: "chain", pronounce: " ʧeɪn ", viet: " chuỗi " },
          { eng: "checkin", pronounce: " checkin ", viet: " đăng ký khi đến " },
          { eng: "confirm", pronounce: " kənˈfɜːm ", viet: " xác nhận " },
          { eng: "expect", pronounce: " ɪksˈpɛkt ", viet: " trông đợi " },
          {
            eng: "housekeeper",
            pronounce: " ˈhaʊsˌkiːpə ",
            viet: " nhân viên dọn phòng ",
          },
          { eng: "notify", pronounce: " ˈnəʊtɪfaɪ ", viet: " thông báo " },
          { eng: "preclude", pronounce: " prɪˈkluːd ", viet: " ngăn cản " },
          {
            eng: "reservation",
            pronounce: " ˌrɛzəˈveɪʃən ",
            viet: " sự đặt chỗ trước ",
          },
          { eng: "quote", pronounce: " kwəʊt ", viet: " báo giá " },
          { eng: "rate", pronounce: " reɪt ", viet: " mức giá " },
          { eng: "service", pronounce: " ˈsɜːvɪs ", viet: " dịch vụ " },
        ],
      },
      {
        topicId: 7,
        topicName: "General Travel",
        wordlist: [
          { eng: "agent", pronounce: "ˈeɪʤənt", viet: "đại lý" },
          { eng: "announcement", pronounce: "əˈnaʊnsmənt", viet: "thông báo" },
          {
            eng: "beverage",
            pronounce: "ˈbɛvərɪʤ",
            viet: "thức uống, đồ uống",
          },
          { eng: "blanket", pronounce: "ˈblæŋkɪt", viet: "Chăn, mền" },
          { eng: "board", pronounce: "bɔːd", viet: "lên máy bay" },
          { eng: "claim", pronounce: "kleɪm", viet: "nhận lại" },
          { eng: "delay", pronounce: "dɪˈleɪ", viet: "trì hoãn" },
          { eng: "depart", pronounce: "dɪˈpɑːt", viet: "khởi hành" },
          {
            eng: "embarkation",
            pronounce: "ˌɛmbɑːˈkeɪʃən",
            viet: "sự cho lên tàu",
          },
          {
            eng: "itinerary",
            pronounce: "aɪˈtɪnərəri",
            viet: "hành trình, lịch trình",
          },
          {
            eng: "prohibit",
            pronounce: "prəˈhɪbɪt",
            viet: "cấm, ngăn cấm, ngăn chặn",
          },
          { eng: "valid", pronounce: "ˈvælɪd", viet: "có hiệu lực" },
        ],
      },
      {
        topicId: 8,
        topicName: "Business Planning",
        wordlist: [
          {
            eng: "Correspondence",
            pronounce: "kɒrɪsˈpɒndəns",
            viet: "thư từ, quan hệ thư từ",
          },
          { eng: "assemble", pronounce: "əˈsɛmbl", viet: "thu thập, tập hợp" },
          {
            eng: "beforehand",
            pronounce: "bɪˈfɔːhænd",
            viet: "sẵn, có sẵn, trước, sớm",
          },
          {
            eng: "complication",
            pronounce: "kɒmplɪˈkeɪʃən",
            viet: "sự phức tạp",
          },
          {
            eng: "courier",
            pronounce: "kʊrɪə",
            viet: "người đưa thư, chuyển phát",
          },
          {
            eng: "express",
            pronounce: "ɪksˈprɛs",
            viet: "tốc hành, nhanh, hỏa tốc",
          },
          { eng: "fold", pronounce: "fəʊld", viet: "gấp, gập" },
          {
            eng: "layout",
            pronounce: "leɪaʊt",
            viet: "sự bố trí, trang trí giấy",
          },
          { eng: "mention", pronounce: "mɛnʃən", viet: "đề cập" },
          { eng: "petition", pronounce: "pɪˈtɪʃən", viet: "sự kiến nghị" },
          { eng: "proof", pronounce: "pruːf", viet: "tìm lỗi, kiểm lỗi" },
          {
            eng: "proof",
            pronounce: "pruːf",
            viet: "bằng chứng, chứng cớ",
          },
          { eng: "revise", pronounce: "rɪˈvaɪz", viet: "sửa lại" },
        ],
      },
    ],
  },
  {
    courseId: 3,
    courseName: "toeic 300000++",
    courseTopics: [
      {
        topicId: 1,
        topicName: "Contract",
        wordlist: [
          { eng: "Address", pronounce: "əˈdrɛs", viet: "Giải quyết (vấn đề)" },
          { eng: "Avoid", pronounce: "əˈvɔɪd", viet: "Tránh" },
          {
            eng: "Demonstrate",
            pronounce: "ˈdɛmənstreɪt",
            viet: "Bày tỏ, biểu lộ, cho thấy",
          },
          { eng: "Develop", pronounce: "dɪˈvɛləp", viet: "Phát triển" },
          { eng: "Evaluate", pronounce: "ɪˈvæljʊeɪt", viet: "Đánh giá" },
          { eng: "Gather", pronounce: "ˈgæðə", viet: "Tập hợp, thu thập" },
          { eng: "Offer", pronounce: "ˈɒfəˌ", viet: "Đề xuất, đề nghị" },
          { eng: "Primarily", pronounce: "ˈpraɪmərɪli", viet: "Chính" },
          { eng: "Risk", pronounce: "rɪsk", viet: "Sự rủi ro" },
          { eng: "Strategy", pronounce: "ˈstrætɪʤi", viet: "Chiến lược" },
          {
            eng: "Strong",
            pronounce: "strɒŋ",
            viet: "Khỏe mạnh, tốt, bền bỉ, …",
          },
          {
            eng: "Substitution",
            pronounce: "sʌbstɪˈtjuːʃən",
            viet: "Sự thay thế",
          },
        ],
      },
      {
        topicId: 1,
        topicName: "Marketing",
        wordlist: [
          { eng: "advanced", pronounce: " ədˈvɑːnst ", viet: " tiên tiến " },
          { eng: "chain", pronounce: " ʧeɪn ", viet: " chuỗi " },
          { eng: "checkin", pronounce: " checkin ", viet: " đăng ký khi đến " },
          { eng: "confirm", pronounce: " kənˈfɜːm ", viet: " xác nhận " },
          { eng: "expect", pronounce: " ɪksˈpɛkt ", viet: " trông đợi " },
          {
            eng: "housekeeper",
            pronounce: " ˈhaʊsˌkiːpə ",
            viet: " nhân viên dọn phòng ",
          },
          { eng: "notify", pronounce: " ˈnəʊtɪfaɪ ", viet: " thông báo " },
          { eng: "preclude", pronounce: " prɪˈkluːd ", viet: " ngăn cản " },
          {
            eng: "reservation",
            pronounce: " ˌrɛzəˈveɪʃən ",
            viet: " sự đặt chỗ trước ",
          },
          { eng: "quote", pronounce: " kwəʊt ", viet: " báo giá " },
          { eng: "rate", pronounce: " reɪt ", viet: " mức giá " },
          { eng: "service", pronounce: " ˈsɜːvɪs ", viet: " dịch vụ " },
        ],
      },
      {
        topicName: "General Travel",
        wordlist: [
          { eng: "agent", pronounce: "ˈeɪʤənt", viet: "đại lý" },
          { eng: "announcement", pronounce: "əˈnaʊnsmənt", viet: "thông báo" },
          {
            eng: "beverage",
            pronounce: "ˈbɛvərɪʤ",
            viet: "thức uống, đồ uống",
          },
          { eng: "blanket", pronounce: "ˈblæŋkɪt", viet: "Chăn, mền" },
          { eng: "board", pronounce: "bɔːd", viet: "lên máy bay" },
          { eng: "claim", pronounce: "kleɪm", viet: "nhận lại" },
          { eng: "delay", pronounce: "dɪˈleɪ", viet: "trì hoãn" },
          { eng: "depart", pronounce: "dɪˈpɑːt", viet: "khởi hành" },
          {
            eng: "embarkation",
            pronounce: "ˌɛmbɑːˈkeɪʃən",
            viet: "sự cho lên tàu",
          },
          {
            eng: "itinerary",
            pronounce: "aɪˈtɪnərəri",
            viet: "hành trình, lịch trình",
          },
          {
            eng: "prohibit",
            pronounce: "prəˈhɪbɪt",
            viet: "cấm, ngăn cấm, ngăn chặn",
          },
          { eng: "valid", pronounce: "ˈvælɪd", viet: "có hiệu lực" },
        ],
      },
      {
        topicName: "Business Planning",
        wordlist: [
          {
            eng: "Correspondence",
            pronounce: "kɒrɪsˈpɒndəns",
            viet: "thư từ, quan hệ thư từ",
          },
          { eng: "assemble", pronounce: "əˈsɛmbl", viet: "thu thập, tập hợp" },
          {
            eng: "beforehand",
            pronounce: "bɪˈfɔːhænd",
            viet: "sẵn, có sẵn, trước, sớm",
          },
          {
            eng: "complication",
            pronounce: "kɒmplɪˈkeɪʃən",
            viet: "sự phức tạp",
          },
          {
            eng: "courier",
            pronounce: "kʊrɪə",
            viet: "người đưa thư, chuyển phát",
          },
          {
            eng: "express",
            pronounce: "ɪksˈprɛs",
            viet: "tốc hành, nhanh, hỏa tốc",
          },
          { eng: "fold", pronounce: "fəʊld", viet: "gấp, gập" },
          {
            eng: "layout",
            pronounce: "leɪaʊt",
            viet: "sự bố trí, trang trí giấy",
          },
          { eng: "mention", pronounce: "mɛnʃən", viet: "đề cập" },
          { eng: "petition", pronounce: "pɪˈtɪʃən", viet: "sự kiến nghị" },
          { eng: "proof", pronounce: "pruːf", viet: "tìm lỗi, kiểm lỗi" },
          {
            eng: "proof",
            pronounce: "pruːf",
            viet: "bằng chứng, chứng cớ",
          },
          { eng: "revise", pronounce: "rɪˈvaɪz", viet: "sửa lại" },
        ],
      },
      {
        topicName: "Business Planning",
        wordlist: [
          { eng: "diversify", pronounce: "daɪˈvɜːsɪfaɪ", viet: "đa dạng hóa" },
          { eng: "enterprise", pronounce: "ˈɛntəpraɪz", viet: "công ty" },
          {
            eng: "everyday",
            pronounce: "ˈɛvrɪdeɪ",
            viet: "hàng ngày, thường ngày",
          },
          { eng: "essential", pronounce: "ɪˈsɛnʃəl", viet: "thiết yếu" },
          { eng: "function", pronounce: "ˈfʌŋkʃən", viet: "hoạt động" },
          { eng: "maintain", pronounce: "meɪnˈteɪn", viet: "duy trì" },
          { eng: "obtain", pronounce: "əbˈteɪn", viet: "thu được" },
          {
            eng: "prerequisite",
            pronounce: "priːˈrɛkwɪzɪt",
            viet: "điều kiện tiên quyết",
          },
          { eng: "quality", pronounce: "ˈkwɒlɪti", viet: "chất lượng" },
          { eng: "smooth", pronounce: "smuːð", viet: "trôi chảy, suôn sẻ" },
          { eng: "source", pronounce: "sɔːs", viet: "nguồn" },
          { eng: "stationery", pronounce: "steɪʃnəri", viet: "văn phòng phẩm" },
        ],
      },
    ],
  },
];

export default data;
